### ISSUE TITLE
Error when selecting "open folder ..."

### ISSUE THREAD

**Issue by ir-tech** [sagiegurari/brackets-portable#10]
When I click "Open folder ..." from file menu I get this error:

//==================================================================
[Window Title]
Location is not available
[Content]
C:\Portables\Brackets\Data\admin\Desktop refers to a location that is unavailable. It could be on a hard drive on this computer, or on a network. Check to make sure that the disk is properly inserted, or that you are connected to the Internet or your network, and then try again. If it still cannot be located, the information might have been moved to a different location.
//==================================================================

But I can't see any opened file/folder from this location.

**Comment by sagiegurari** [comment]
See #3
