### ISSUE TITLE
Brackets not loadnig extensions on new computers

### ISSUE THREAD

**Issue by Noboty** [sagiegurari/brackets-portable#12]
Google has been of no help., so I am posting this here. Brackets portable won't load extensions I installed when using a computer other than the one I used to install them. Do you have any idea why?

**Comment by sagiegurari** [comment]
What exe did you run and what is its path (you can remove sesitive parts from the path)?
Also did only specific extension failed? If so, which one?

**Comment by Noboty** [comment]
None of my extensions will load on computers other than the one I used to install them. Also, I ran the "Brackets.exe" executable that appeared after installing brackets portable to my USB drive. 

the one at flash drive/Bracketsportable/Bracketsportable.exe

**Comment by sagiegurari** [comment]
Do you see your extensions at:
<brackets portable directory>\Data\home\AppData\Roaming\Brackets\extensions\user

**Comment by Noboty** [comment]
I found the problem. I had shortcuts to the exe but it was leading back to the exe in the apps/brackets/ folder instead f the main brackets folde.r After forging a new exe that leads to the exe in the main brackets folder, everything was fine. I am sorry for the waste of time.

**Comment by sagiegurari** [comment]
Good to know. Thanks for the update
