### ISSUE TITLE
Brackets Portable 1.10 not launching

### ISSUE THREAD

**Issue by klinge** [sagiegurari/brackets-portable#13]
Brackets Portable 1.10 downloaded from "latest" is not launching on my computer. 

I did an update-install to the same folder where I had the 1.9 version. After update the program did not start anymore. I also tried a fresh install of 1.10 to a new folder - same problem. I have tried to start the program from the command line. Got no error messages but the app is still not launching. Not finding any log files. 

What could I do to find out what is causing this?

**Comment by sagiegurari** [comment]
I tried to install it on a clean machine and it worked well.
Did the install had any errors? sometimes it fails because the paths are too long in which case you should install on some root folder like c:\brackets.
Can you try that?

**Comment by klinge** [comment]
It seems like it installs without errors. At least I get no error messages. I cannot install to c: but I tried to install to the folder c:\egna\bp. Still not working.

**Comment by dwightblackwell** [comment]
Brackets Portable 1.10 downloaded from "latest" is not launching on my computer/Usb neither. It installed without errors, but not working. I tried to run it from c:\brac and still not working. When I click on the brackets icon to launch, i can see in the Task Manager, it open for about 5 sec, and than it closes.

**Comment by sagiegurari** [comment]
can you try to run the brackets.exe directly from the app\brackets folder?
keep it mind that this way, it is not portable and it will store data on the pc and not on the portable installation but lets try to run brackets directly to see if that works or not.

**Comment by klinge** [comment]
When trying to start brackets.exe directly from the app\brackets folder I get an error message. My OS is in Swedish but loosely translated it says "The program can't start because VCRUNTIME140.dll is missing on the computer".

**Comment by klinge** [comment]
I found that there has been an issue reported for Brackets itself concerning the missing VCRUNTIME140.dll. The issue is now resolved and the needed dependencies added to the brackets installer. This was done around July 10. 

https://github.com/adobe/brackets/issues/13534

**Comment by sagiegurari** [comment]
Ok that's too bad because I can't run that as it will make the entire thing non portable.
The whole point is that you are not really installing anything on your pc and you can take it with you on a portable storage device.
So if they added a dependency and you don't have it installed (in this case vc runtime), than I can't install that for you.
I guess it worked for me on several pcs as I had it already installed.
I'll have to add it as a known issue but can't help with that, only recommend that you manually install the vc runtime.

**Comment by dwightblackwell** [comment]
I opened brackets from my usb flash, and my Win10 pc asked for administrative privilege's.

**Comment by dwightblackwell** [comment]
Ill try to unstall the missing vc dll file when i get a chance. Thanks guys!

**Comment by sagiegurari** [comment]
you mean brackets.exe?

**Comment by dwightblackwell** [comment]
Sorry yes. I mean .exe

Dwight Blakwell

**Comment by sagiegurari** [comment]
strange because they don't ask for admin permissions when running.

**Comment by klinge** [comment]
Hi, I don't really know how to package portable applications, but wouldn't it be possible to include the missing dll among the program files? 

I see that installing it on the computer would brake the "portable concept", but including a dependency among the portable program files would not I guess. 

Is this worth looking into?

**Comment by sagiegurari** [comment]
Unfortunately I'm not sure how to create a portable setup of vc runtime and I have no seen anyone do that before (tried to google a bit about it).
So, ya, to package it and somehow use it, would be good, the 'how' is the issue and i'm not sure if possible.
I'm always open to PRs.

**Comment by klinge** [comment]
Placing the correct version of vcruntime140.dll in the "App/Brackets"-directory makes the application run fine. Seems that it is the 32-bit version of the dll that is required. 

I have never packaged portable applications, but a brief look at other portable apps shows that this is doable, and fairly common. Look for example at Firefox portable which installs a number of required dll:s (vcruntime140.dll is one of them) in the "App/Firefox" and "App/Firefox64" directories.

**Comment by sagiegurari** [comment]
That's great news!!! Thanks for investigating this.
I'll publish a new version with the dll today.

**Comment by sagiegurari** [comment]
Published a new release: https://github.com/sagiegurari/brackets-portable/releases/tag/v1.10.0.2
Thanks for your help

**Comment by klinge** [comment]
I downloaded the latest released, installed it and can confirm that it is working. Thanks for the quick update!
