### ISSUE TITLE
PortableApp gets stuck in starting mode

### ISSUE THREAD

**Issue by keleko34** [sagiegurari/brackets-portable#14]
I am having an issue where brackets portable was shut off mid starting and now I am unable to open it as it states it is in starting mode. sadly many of the articles I looked up dealt with changing PortableApps.comLauncherRuntimeData ini file. in this case it doesnt seem to exist and must be in another location. Any help would be appreciated.

**Comment by sagiegurari** [comment]
please provide some links so I'll know what you are talking about.
Right now, I don't have enough info to help.

**Comment by keleko34** [comment]
http://notemy.work/fix-another-instance-abcapp-already-running-error/
https://superuser.com/questions/586090/how-can-i-fix-another-instance-of-someapp-is-currently-closing-error-message
![starting](https://user-images.githubusercontent.com/7937774/31339734-1c53f4d8-ad04-11e7-929d-45626774d3a2.JPG)
![dir](https://user-images.githubusercontent.com/7937774/31339739-1e832b02-ad04-11e7-9239-9faa3a291a8c.JPG)

**Comment by keleko34** [comment]
This seems to happen if the app is closed after the initial install and then attempted to reopen a second time. deleting the entire folder and reinstalling it allows it to be opened once.

**Comment by keleko34** [comment]
I have noticed in %APPDATA%/local/temp it creates the ns???.tmp folder when attempting to start with only System.dll and launcher.ini but both the data dir and this dir a PortableApps.comLauncherRuntimeData file is not created. This may have something to do with the portable settings implemented for the app?

**Comment by sagiegurari** [comment]
I override these env vars when launching

[Environment]
APPDATA=%PAL:DataDir%\home\AppData\Roaming
USERPROFILE=%PAL:DataDir%\home

So the app data dir is actually inside the data folder of the portable app and not in your user home

**Comment by keleko34** [comment]
ok will try tomorrow

**Comment by sagiegurari** [comment]
closing this for now. if there is a real issue please reopen it.
