### ISSUE TITLE
"FileRepMalware" detected by AVG virus checker...

### ISSUE THREAD

**Issue by PaulANormanNZ** [sagiegurari/brackets-portable#16]
Hi,

Looking forward to using a portable version. I use PortableApps s thought this might be ideal to use and put my friends on to as well.

Had trouble downloading the latest (1 October) in the browser - AVG would jump in. 
So I  successfully used a file downloader,  and even after manually scanning the file and AVG saying its ok, AVG jumps in when I try to run the .exe for the first time .

https://github.com/sagiegurari/brackets-portable/releases/download/v1.11.0.1/BracketsPortable_Release_1.11_English.paf.exe

Screen shot attached.

Might be a false positive, but AVG was more ferocious on this than I've seen it behave for ages.
Thought  you'd like to know,.,,

Any advice on what to do please?

(I also just tried to download the file from SourceForge in the Browser and got the result shown in the second screen shot below..).

TIA
paul

![image](https://user-images.githubusercontent.com/457267/32412211-4bad7af4-c255-11e7-9b05-15dc868a6fa5.png)

P.S. I also just tried to download the file from SourceForge in the Browser and got this result...

![image](https://user-images.githubusercontent.com/457267/32412275-f07b7f9e-c256-11e7-9e19-f2e44bd1eaf4.png)

**Comment by sagiegurari** [comment]
its not an issue.
it means low reputation meaning this exe is not common and unknown to avg.
google FileRepMaleware to be sure. I also see it with other paf software I install and it is not something I have an ability to control.

**Comment by PaulANormanNZ** [comment]
Hi,
Thanks for that.

What's it likely to be upset with, PortableApps .paf,exe technology has been around for ages, is it something in Brackets itself?

Here below is a parallel problem, and AVG recommend that the app be uploaded to their site - 

http://www.avg.com/submit-sample

That's hard for me to do as AVG is upset with it, I'll try, but maybe it'd be better coming form you as the developer to them? :-)

Here's some more info in case any one else encounters this.., (from a technician's post at AVG Forum): 

https://support.avg.com/answers?id=906b0000000DywhAAC

"Balasubramanian (AVG Technologies) 

"...The reason is because the PTS Primo chart setup file that you are trying to install is considered as a threat.
If this is a trusted program then please disable AVG Antivirus program temporarily as mentioned in this article: http://support.avg.com/SupportArticleView?urlname=How-to-use-Passive-Mode and install PTS Primo application.
Enable AVG Antivirus and add the PTS application installed path to AVG's exclusion list as mentioned in this article: http://support.avg.com/SupportArticleView?urlname=How-to-make-exclusions-from-all-scans-and-shields .
Before adding it to exception, please provide the PTS Primo setup file information to us through this link: http://www.avg.com/submit-sample which will help us to analyze the file and add it to whitelist."

**Comment by sagiegurari** [comment]
developer title is an overstatement :)
brackets is developed by adobe, not me and I only package it with an installer + launcher developed by paf and again, not me.
besides I'm guessing with every new version, it will reoccur as it will be a new exe with new name.

**Comment by rhosimani** [comment]
Thanks Paul,

This does not cause me any inconvenience.
In any case, I think it is preferable that you let me know before a
suspicion that you do not.

Thank you again.
Sincerely
*Rubén H. Osimani*

2017-11-05 2:22 GMT-03:00 PaulANormanNZ <notifications@github.com>:
