### ISSUE TITLE
AVG threat detection

### ISSUE THREAD

**Issue by mjakubowskilkr** [sagiegurari/brackets-portable#17]
Hi,
I'm trying to decompress portable version but my AVG Business detects virus (or any other danger content) in it.
![brackets](https://user-images.githubusercontent.com/25199984/33163399-a71788bc-d02e-11e7-93f2-78b507bad4a3.png)
How to solve it?

**Comment by sagiegurari** [comment]
can't read that. is it same avg issue as in #16 ?

**Comment by mjakubowskilkr** [comment]
No, that detects IDP.Generic.0eeb90c741fb.3.2 and removes installer file. So I can't decompress it.

**Comment by sagiegurari** [comment]
tried to google it, didn't get any results.
I have no idea what that means and where it came from.

**Comment by mjakubowskilkr** [comment]
I've disabled av for a while, then unpacked it. Now it works and av doesn't show any thread detected.

**Comment by sagiegurari** [comment]
Ok. Avg doesn't like portable apps for some reason. Happy you worked around it
