### ISSUE TITLE
Live Preview not working

### ISSUE THREAD

**Issue by AMWARD** [sagiegurari/brackets-portable#4]
When I click Live Preview it doesn't work. Is this because it's portable?

**Comment by sagiegurari** [comment]
is your chrome portable as well or is it installed?

**Comment by AMWARD** [comment]
Installed

**Comment by sagiegurari** [comment]
OK, I'll be able to check it tomorrow.
Last I saw it was fine but that was a while ago.

**Comment by sagiegurari** [comment]
just validated it and live preview works fine.
I'm using latest release and chrome installed (and its also set as my default browser).

Brackets:
Release 1.5 build 1.5.0-16538 (release cf9cf4698) 
build timestamp: Mon Oct 12 2015 13:14:22 GMT+0100
Chrome:
Version 48.0.2547.0 dev-m

Naturally I did live preview for a html file and no something else.
So it is not an issue with the portable version of brackets, so maybe you got an issue with brackets itself or your system.

**Comment by sagiegurari** [comment]
Closing this issue as this is working fine and I'm not getting any other feedback of the opposite.
