### ISSUE TITLE
Can't install / launch

### ISSUE THREAD

**Issue by metawops** [sagiegurari/brackets-portable#5]
On my office PC (Windows 7) I'm not allowed to 
- install the original Brackets MSI (admin rights needed, don't have them)
- download .exe files from the internet.

I donwloaded the .ZIP source but after unzipping when I doubleclick the BracketsPortable.exe I just geht an error message:
![2015-12-02 11_32_54-brackets portable portableapps com launcher](https://cloud.githubusercontent.com/assets/376090/11528674/8c9d7868-98e8-11e5-8ed9-abc36ce7283c.png)

I don't want to install Brackets onto a USB drive but rather on my local harddrive ...

Any tips much appreciated! Thx!

**Comment by sagiegurari** [comment]
you need to download the paf exe and not source zip.
the paf exe is a non admin needed installer that will install the portable brackets.
installation of portable brackets actually means unzip, nothing else so you don't need admin rights to run it.
the source zip is not for runtime, but it is a copy of the repo at the time of the release creation and you don't need it.

**Comment by sagiegurari** [comment]
is the paf exe working?

**Comment by sagiegurari** [comment]
closed due to wrong usage and no feedback.

**Comment by metawops** [comment]
Yes, sorry, I haven't had the time to test this yesterday. But I just downlaoded it (luckily I was able to download a .exe file; that's normally not allowed, so if this could be .ZIPped that would be great) and everything seems to work! :)
Makes my day! Thanks so much for your kind help and caring!! :)

**Comment by sagiegurari** [comment]
Thanks, good to hear it works well for you.
