### ISSUE TITLE
1.6 is out

### ISSUE THREAD

**Issue by leeoniya** [sagiegurari/brackets-portable#6]
just a heads up :)

**Comment by sagiegurari** [comment]
you are right. I subscribed to their blog to get news of new releases: http://blog.brackets.io/
seems they were too lazy to write about it :)
I'll update and publish a new release

**Comment by sagiegurari** [comment]
1.6 released: https://github.com/sagiegurari/brackets-portable/releases/tag/1.6.0
Thanks a lot for notifying me.

**Comment by leeoniya** [comment]
glad to have made such a fundamental contribution to this project ;)
