### ISSUE TITLE
PHP code quality tools

### ISSUE THREAD

**Issue by ghost** [sagiegurari/brackets-portable#7]
Hi

I set php.exe folder to the path variable and when working with Brackets it worked. Now I tried brackets portable and it doesn't recognize php on my machine. Any idea why is that?

**Comment by sagiegurari** [comment]
how do you set it? the launcher changes the following 2 env vars:

APPDATA=%PAL:DataDir%\home\AppData\Roaming
USERPROFILE=%PAL:DataDir%\home

**Comment by ghost** [comment]
Computer -> properties -> advanced system settings -> environment variables -> system variables

**Comment by sagiegurari** [comment]
can you show me the full value?

**Comment by ghost** [comment]
You mean the full path to the php folder?
...;C:\@Downloads\BracketsPortable\PHP

or the full value of the path variable?
C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\16.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\16.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl\Win64;C:\Program Files (x86)\CollabNet;C:\Program Files (x86)\Embarcadero\RAD Studio\10.0\bin;C:\Users\Public\Documents\RAD Studio\10.0\Bpl;C:\Program Files (x86)\Embarcadero\RAD Studio\10.0\bin64;C:\Users\Public\Documents\RAD Studio\10.0\Bpl\Win64;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%DXVCL%\Library\RS17;%DXVCL%\Library\RS17\Win64;C:\Program Files\MongoDB\Server\3.2\bin;C:\@Downloads\BracketsPortable\PHP

**Comment by ghost** [comment]
it works now, not sure why and how

**Comment by sagiegurari** [comment]
magic :)
